### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by shubhendusaurabh** [L33T-KR3W/push-dir#17]
I'm trying to run following command in windows

`push-dir --dir-build --branch=gh-pages`

but it gives following error

> aborted: problem checking if detached head

npm version: 3.9.1
git version: git version 1.9.5.msysgit.0

**Comment by scott113341** [comment]
Thanks for the report, @shubhendusaurabh!

First, it looks like you have a typo in your usage, it should be: `push-dir --dir=build --branch=gh-pages` (you have a hyphen after the `--dir` flag).  

Second, our code has a windows [incompatibility](https://github.com/L33T-KR3W/push-dir/blob/v0.2.1/index.js#L142-152) currently, I'll work on a fix today!

**Comment by scott113341** [comment]
@shubhendusaurabh, I have merged in the code that I believe will fix the issue you're having!  When you get a chance, update your version of push-dir with `npm install push-dir@latest` and let us know if you're still running into any issues.  Thanks!

**Comment by shubhendusaurabh** [comment]
@scott113341 it works now. Thanks for the so quick fix

**Comment by scott113341** [comment]
Glad to hear it!
