### ISSUE TITLE
Forward output from the githooks to stdout

### ISSUE THREAD

**Issue by bartkozal** [L33T-KR3W/push-dir#21]
When you push to a remote repository like Heroku, Dokku etc. would be cool to see the output from the remote hooks of these services.

**Comment by scott113341** [comment]
Hi @bkzl, thanks for the suggestion. I think it will be easy to redirect output from the sub processes to the main process's stdout/stderr

**Comment by scott113341** [comment]
Published in version `0.4.0`.  Include the `--verbose` flag to get all the stdout/stderr from subcommands.  Thanks for the suggestion @bkzl!

**Comment by bartkozal** [comment]
✨Super cool! Thank you! ✨
